---
site:
  title: OpenShift 5 Early Access
  url: https://github.com/rhpds/ocp5-ea-showroom
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/patternfly-6/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: css/vendor/tabs.css
      contents: ./node_modules/@asciidoctor/tabs/dist/css/tabs.css
    - path: js/vendor/tabs.js
      contents: ./node_modules/@asciidoctor/tabs/dist/js/tabs.js
    - path: partials/footer-scripts.hbs
      contents: |
        <script src="{{uiRootPath}}/js/vendor/clipboard.js"></script>
        <script src="{{uiRootPath}}/js/site.js"></script>
        <script async src="{{uiRootPath}}/js/vendor/highlight.js"></script>
        <script async src="{{uiRootPath}}/js/vendor/tabs.js"></script>
    - path: partials/head-styles.hbs
      contents: |
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/vendor/tabs.css">

asciidoc:
  extensions:
    - '@asciidoctor/tabs'
  attributes:
    showroom-collection-version: v1.5.2

output:
  dir: ./www
